services:
  db:
    image: mysql:9.0.1
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: storedb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
  app:
    build: .
    container_name: online_store
    ports:
      - "18080:18080"
    depends_on:
      - db

volumes:
  db_data:
